---
title: "Philippe Heymans Smith"
author: "Científico de datos"
date: "`r Sys.Date()`" 
output: rmdformats::downcute
---


#### Heredia, Costa Rica *·* (+506) 8447-8088 *·* pheymanss@gmail.com *·* [github](https://github.com/pheymanss)

Científico de datos, desarrollador de R y entusiasta de ética en aplicaciones de machine learning. Me apasiona crear herramientas poderosas que sean a la vez flexibles y fáciles de usar, y quiero enfocarme en justicia algorítmica en los procesos de prototipado y produccionización de modelos.

## Educación

**MSc en Ciencia de Datos e Inteligencia Artificial**  
Data ScienceTech Institute  
2020 - Presente   

**Bsc, Ciencias Actuariales**  
Universidad de Costa Rica, Escuela de Matemática  
2013 - 2018   

## Habilidades técnicas

```{r fig.width=6, fig.height=6, fig.align='center', eval=FALSE}
habilidades_tecnicas <- list(
  `Profundo entendimiento de técnicas de modelación con machine learning` = 
    c('Modelos de árboles (tree boosting, random forests, XGBoost)',
      'DBSCAN',
      'Clustering con mixturas gausianas',
      'Redes neuronales artificiales',
      'Emsambles de modelos',
      'Análisis de series de tiempo',
      'Análisis de sobrevivencia'),
  `Desarrollo en R` = 'proficiencia sobresaliente con data.table y purrr',
  `Desarrollo de paquetes de R con documentación impecable` = 'autor del paquete {chronicle} publicado en CRAN'
  `Visualización de datos` = 'alta proficiencia con ggplot2 y htmlwidgets',
  `Experiencia demostrable con análisis de big data` = 'proyectos con más de 200MM de observaciones',
  `Manejo sólido de Python`
  `Conocimiento sólido de SQL`,
  `Manejo sólido de principios generales de diseño`,
  `Sólido entendimiento sobre sistemas distribuidos de almacenamiento de datos`,
  `Sólidas habilidades de desarrollo en Shiny`)
```

## Experiencia Profesional

**Desarrollo Open Source**  
Desarrollador de R  2020 -- Presente 

* Autor de [chronicle](https://github.com/pheymanss/chronicle), un paquete de R que permite crear reportes de R sin fricción, con una sintaxis secuencial inspirada en keras/ggplot2. Exitosamente publicado en CRAN en enero del 2021, y presentado en el meetup de personas usuarias de R conectaR 2021, así como en la conferencia useR! 2021.

**Growth Acceleration Partners**  
Advanced Data Scientist, Development US  
San José, Costa Rica. Abr 2021 -- Presente

* Desarrollo de modelos de scoring para diseño de audiencias, incluyendo investigación en definición de audiencias médicas de acuerdo al estándar de codificación ICD-10.
* Desarrollo de una herramienta para crear queries de SQL automáticamente, ajustándose a los distintos esquemas de definición que se utilizan en el proyecto.
* Como parte del Centro de Excelencia de Analytics, establecimiento de canales de colaboración con universidades, grupos de interés y organizaciones de liderazgo femenino en STEM. En esfuerzo conjunto se prepararon talleres y webinars para presentar técnicas, oportunidades y desafíos a los que se enfrenta el gremio de la ciencia de datos, con el fin de llevarlo a un futuro justo, diverso y ético. 

**Mastercard SJO Center of Excellence**  
Associate Consultant, Advanced Analytics.  
San José, Costa Rica. Jul 2019 -- Abr 2021


* Desarrollo de productos de analítica avanzada para distintas intituciones financieras del continente, apalancándose de los cientos de GB de data transaccional de la compañía. Proyectos como segmentaciones compartamentales, diagnósticos de desempeño de campañas, modelos de migración de productos, diagnósticos de autorizaciones y fraudes, entre otros esfuerzos menores.
* Todos los proyectos entregados incluyeron meticulosas exposiciones técnicas y metodológicas para involucrados internos y externos, de perfiles mayoritariamente no técnicos.
* Desarrollo de dos paquetes de R propietarios, incluyendo más de 100 funciones de uso generalizado en el equipo, facilitando tareas de transformación, limpieza y comunicación de los datos.
* Diseñado e impartido entrenamientos de R para equipos no especializados de la región, adicionales a sesiones de capacitación semanales dentro del equipo técnico.

**Quanto Soluciones Analíticas y Cuantitativas S.A.**  
Analista Financiero, Departamento de Métodos Matemáticos
San José, Costa Rica. Abr 2018 -- Jul 2019

* Reescritura del algoritmo de calibración de sensibilidad macroeconómica para los modelos de riesgo de liquidez.
* Ejecución del despliegue y diagnóstico de 10 funcionalidades adicionales de la herramienta de riesgo de liquidez para uno de los principales clientes de la empresa.
* Soporte técnico y metodológico para clientes en el uso de las herramientas de gestión de riesgo.

## Experiencia Académica

**Análisis de sentimiento para textos cortos informales en español**
Procesamiento de lenguaje natural  
Desarrollado en R, Ago 2016 --Jul 2017  

* Construcción de una herramienta de clasificación de texto bajo un riguroso marco matemático, presentando el proceso de scoring como una medida signada.

**Análisis del mercado de flores a través de búsquedas de Google**
Análisis de series de tiempo  
Desarrollado en R, Nov 2017 -- Dec 2017

* Utilizando metodologías básicas de series de tiempo como ARIMA(p,q), se caracterizan las fluctuaciones y tasa de crecimiento esperado en el mercado de flores, basándose en la serie de tiempo de búsquedas de Google de la palabra "flower".

**Evaluación de estrategias de apuestas en línea de la MLB**
Backtesting  
Desarrollado en VBA, Jun 2016 -- Jul 2016

* Se ejecutan simulaciones de desempeño de distintas estrategias de apuestas para un individuo sin conocimiento previo del deporte, basándose solamente en información que podría ser minada de páginas de apuestas deportivas. Se desarrolla una versión modificada de martingala que obtiene alta probabilidad de ganancia en todo subconjunto del periodo de estudio.
